# Estos dos datos te los da SonarCloud en la misma pantalla donde te dio el Token
sonar.projectKey=Aca_Pones_El_Project_Key
sonar.organization=Aca_Pones_Tu_Organizacion

# Le decimos dónde está el código de producción y dónde están los tests
sonar.sources=src
sonar.tests=tests,features

# Opcional, pero recomendado: le pasamos el reporte de cobertura de Vitest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.qualitygate.wait=true